version: '3.8'
services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  api:
    build: .
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/fooddb
      - EXCEL_PATH=/data/task2.xlsx
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /mnt/data:/data:ro

volumes:
  mongo-data:
